src/QualityHats/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace QualityHats.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 1)]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Unit Price")]
        public decimal UnitPrice { get; set; }

        public int SupplierID { get; set; }
        public int CategoryID { get; set; }   
           
        public string Description { get; set; }
        public string ImagePath { get; set; }

        public Supplier Supplier { get; set; }
        public Category Category { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }
    }
}

src/QualityHats/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityHats.Data;
using QualityHats.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;

namespace QualityHats.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public ProductsController(ApplicationDbContext context, IHostingEnvironment hEnv)
        {
            _context = context;
            _hostingEnv = hEnv;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Category).Include(p => p.Supplier);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            var product = await _context.Products.Include(p => p.Category)
                                           .Include(p => p.Supplier)
                                           .AsNoTracking()
                                           .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product
                                                , IList<IFormFile> _files)
        {
            var relativeName = "";
            var fileName = "";

            if (_files.Count < 1)
            {
                relativeName = "/images/Default.jpg";
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                      .Parse(file.ContentDisposition)
                                      .FileName
                                      .Trim('"');
                    //Path for localhost
                    relativeName = "/images/ProductImages/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;

                    using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                    {
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }
            }
            product.ImagePath = relativeName;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " + "Try again, and if the problem persists " + "see your system administrator.");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product
                                              , IList<IFormFile> _files, byte[] rowVersion)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }
            var relativeName = "";
            var fileName = "";
            var productToUpdate = await _context.Products.AsNoTracking().SingleOrDefaultAsync(s => s.ProductID == id);

            if (productToUpdate == null)
            {
                Product deleteProduct = new Product();
                await TryUpdateModelAsync(deleteProduct);
                ModelState.AddModelError(string.Empty, "Unable to save changes. The product was deleted by another user.");
                ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", deleteProduct.CategoryID);
                ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", deleteProduct.SupplierID);
                return View(deleteProduct);
            }


            if (_files.Count < 1)
            {
                relativeName = productToUpdate.ImagePath;
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                      .Parse(file.ContentDisposition)
                                      .FileName
                                      .Trim('"');
                    //Path for localhost
                    relativeName = "/images/ProductImages/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;

                    using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                    {
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }
            }
            productToUpdate.ImagePath = relativeName;
            _context.Entry(productToUpdate).Property("RowVersion").OriginalValue = rowVersion;

            if (await TryUpdateModelAsync<Product>(
                                productToUpdate,
                                "",
                                s => s.ProductName, s => s.UnitPrice, s => s.SupplierID, s => s.CategoryID, s => s.Description,
                                s => s.ImagePath))
            {
                try
                {
                    _context.Update(productToUpdate);
                    await _context.SaveChangesAsync();
                    ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
                    ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var databaseEntity = await _context.Products
                                           .AsNoTracking()
                                           .SingleAsync(d => d.ProductID == ((Product)exceptionEntry.Entity).ProductID);
                    var databaseEntry = _context.Entry(databaseEntity);                    
                    ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                   + "was modified by another user after you got the original value. The "
                   + "edit operation was canceled and the current values in the database "
                   + "have been displayed. If you still want to edit this record, click "
                   + "the Save button again. Otherwise click the Back to List hyperlink.");
                    productToUpdate.RowVersion = (byte[])databaseEntry.Property("RowVersion").CurrentValue;
                    ModelState.Remove("RowVersion");
                }

            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);


            //if (ModelState.IsValid)
            //{
            //    try
            //    {

src/QualityHats/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QualityHats.Models;
using QualityHats.Data;
using Microsoft.AspNetCore.Authorization;

namespace QualityHats.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Member")]
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Return the view
            return View(cart);
        }

        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = _context.Products
                .Single(product => product.ProductID == id);
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedProduct, _context);
            // Go back to the main store page for more shopping
            //return RedirectToAction("Index", "Products");
            return RedirectToAction("Index", "MemberProducts");
        }    
           
        public ActionResult EmptyCart()
        {
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.EmptyCart(_context);
            // Go back to the main store page for more shopping
            //return RedirectToAction("Index", "Products");
            return RedirectToAction("Index", "MemberProducts");
        }


        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int itemCount = cart.RemoveFromCart(id, _context);
            return Redirect(Request.Headers["Referer"].ToString());
        }

    }
}

src/QualityHats/ViewComponents/ShoppingCartViewModelViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QualityHats.Data;
using QualityHats.Models;
using QualityHats.Models.ShoppingCartViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QualityHats.ViewComponents
{
    public class ShoppingCartViewModelViewComponent:ViewComponent
    {
        private readonly ApplicationDbContext _context;
        public ShoppingCartViewModelViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            return View(ReturnCurrentCartViewModel());
        }

        public ShoppingCartViewModel ReturnCurrentCartViewModel()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(_context),
                CartGST = cart.GetGst(_context),
                CartSub = cart.GetTotalSubAmount(_context),
                CartTotal = cart.GetTotalAmount(_context)
            };
            return viewModel;
        }

    }
}

src/QualityHats/Views/Products/Create.cshtml
@model QualityHats.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoryID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CategoryID" class ="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SupplierID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID"></select>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="UnitPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @*<input asp-for="Description" class="form-control" />*@
                <textarea asp-for="Description" class="form-control" cols="40" rows="5"></textarea>
                <span class="text-danger field-validation-valid" data-valmsg-for="Description" data-valmsg-replace="true"></span>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">         
            <label asp-for="ImagePath" class="col-md-2 control-label">Image</label>
            <div class="col-md-4">
                <span asp-validation-for="ImagePath" class="text-danger" />
                <input type="file" name="_files" id="_files" onchange="imagePreview( this );" accept="image/*" />
            </div>           
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Image Preview</label>
            <div class="col-md-4">
                <img id="ProductImage" class="img-rounded" style="width: 300px; height: 200px;" src="@Href("~/images/Default.jpg")" alt="Product Image">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/QualityHats/Views/Products/Delete.cshtml
@model QualityHats.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3> @TempData["TutorialUsed"] </h3>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Image
        </dt>
        <dd>
            <div class="col-md-4">
                <img id="ProductImage" style="width: 300px; height: 300px;" src="@Href("~" + Model.ImagePath)" alt="Product Image" onerror="this.onerror = null; this.src = '@Href("~/images/default_hat.jpg")'">
            </div>
        </dd>
        
       
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" asp-for="RowVersion" />
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/QualityHats/Views/Products/Details.cshtml
@model QualityHats.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt class="col-md-4 control-label">
            @Html.DisplayNameFor(model => model.ProductName)          
        </dt>
        <dd >
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt class="col-md-4 control-label">
            Category
        </dt>
        <dd>
            @Html.DisplayFor(model => Model.Category.CategoryName)
        </dd>

        <dt class="col-md-4 control-label">
            Supplier
        </dt>
        <dd >
            @Html.DisplayFor(model => Model.Supplier.SupplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Image
        </dt>
        <dd>
            <div class="col-md-4">
                <img id="ProductImage" style="width: 300px; height: 300px;" src="@Href("~" + Model.ImagePath)" alt="Product Image" onerror="this.onerror = null; this.src = '@Href("~/images/default_hat.jpg")'">
            </div>
        </dd>
        
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/QualityHats/Views/Products/Edit.cshtml
@model QualityHats.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" asp-for="RowVersion" />

        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoryID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
                <span asp-validation-for="CategoryID" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="SupplierID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID"></select>
                <span asp-validation-for="SupplierID" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="UnitPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Description" class="form-control" cols="40" rows="5"></textarea>
                <span class="text-danger field-validation-valid" data-valmsg-for="Description" data-valmsg-replace="true"></span>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Image</label>
            <div class="col-md-4">
                <img id="ProductImage" style="width: 300px; height: 300px;" src="@Href("~" + Model.ImagePath)" alt="Product Image" onerror="this.onerror = null; this.src = '@Href("~/images/default_hat.jpg")'">
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ImagePath" class="col-md-2 control-label">Change Image</label>
            <div class="col-md-4">
                <span asp-validation-for="ImagePath" class="text-danger" />
                <input type="file" name="_files" id="_files" onchange="imagePreview( this );" accept="image/*" />
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
                <input type="submit" value="Save" class="btn btn-yellow" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/QualityHats/Views/Products/Index.cshtml
@model IEnumerable<QualityHats.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h2>Products List</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                  Image
            </th>          
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        var imgUrl = @Href("~" + item.ImagePath);
        var errImg = @Href("~/images/default_hat.jpg");
        <tr>
            <td>
                <img style="width: 150px; height: auto;" class ="img-rounded" src="@imgUrl" alt="Product Image" onerror="this.onerror = null; this.src = '@errImg'">
            </td>
            <td width="200px">
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td class="wrapper" width="150px">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
            </td>

            @*<td>
                <a  asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@item.ProductID">
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                    Add To Cart
                </a>
            </td>*@

        </tr>
}
    </tbody>
</table>

<div>
    @*@await Component.InvokeAsync("ShoppingCartViewModel")*@
</div>