src/QualityHats/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace QualityHats.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/QualityHats/Controllers/MemberProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityHats.Data;
using QualityHats.Models;
using Microsoft.AspNetCore.Authorization;

namespace QualityHats.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Member")]
    public class MemberProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberProductsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: MemberProducts
        public async Task<IActionResult> Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var items = cart.GetCartItems(_context);
            var applicationDbContext = _context.Products.Include(p => p.Category).Include(p => p.Supplier);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MemberProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: MemberProducts/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "Address");
            return View();
        }

        // POST: MemberProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "Address", product.SupplierID);
            return View(product);
        }

        // GET: MemberProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "Address", product.SupplierID);
            return View(product);
        }

        // POST: MemberProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "Address", product.SupplierID);
            return View(product);
        }

        // GET: MemberProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: MemberProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

src/QualityHats/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityHats.Data;
using QualityHats.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;

namespace QualityHats.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public ProductsController(ApplicationDbContext context, IHostingEnvironment hEnv)
        {
            _context = context;
            _hostingEnv = hEnv;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Category).Include(p => p.Supplier);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            var product = await _context.Products.Include(p => p.Category)
                                           .Include(p => p.Supplier)
                                           .AsNoTracking()
                                           .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product
                                                , IList<IFormFile> _files)
        {
            var relativeName = "";
            var fileName = "";

            if (_files.Count < 1)
            {
                relativeName = "/images/Default.jpg";
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                      .Parse(file.ContentDisposition)
                                      .FileName
                                      .Trim('"');
                    //Path for localhost
                    relativeName = "/images/ProductImages/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;

                    using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                    {
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }
            }
            product.ImagePath = relativeName;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " + "Try again, and if the problem persists " + "see your system administrator.");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,CategoryID,Description,ImagePath,ProductName,SupplierID,UnitPrice")] Product product
                                              , IList<IFormFile> _files, byte[] rowVersion)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }
            var relativeName = "";
            var fileName = "";
            var productToUpdate = await _context.Products.AsNoTracking().SingleOrDefaultAsync(s => s.ProductID == id);

            if (productToUpdate == null)
            {
                Product deleteProduct = new Product();
                await TryUpdateModelAsync(deleteProduct);
                ModelState.AddModelError(string.Empty, "Unable to save changes. The product was deleted by another user.");
                ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", deleteProduct.CategoryID);
                ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", deleteProduct.SupplierID);
                return View(deleteProduct);
            }


            if (_files.Count < 1)
            {
                relativeName = productToUpdate.ImagePath;
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                      .Parse(file.ContentDisposition)
                                      .FileName
                                      .Trim('"');
                    //Path for localhost
                    relativeName = "/images/ProductImages/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;

                    using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                    {
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }
            }
            productToUpdate.ImagePath = relativeName;
            _context.Entry(productToUpdate).Property("RowVersion").OriginalValue = rowVersion;

            if (await TryUpdateModelAsync<Product>(
                                productToUpdate,
                                "",
                                s => s.ProductName, s => s.UnitPrice, s => s.SupplierID, s => s.CategoryID, s => s.Description,
                                s => s.ImagePath))
            {
                try
                {
                    _context.Update(productToUpdate);
                    await _context.SaveChangesAsync();
                    ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
                    ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var databaseEntity = await _context.Products
                                           .AsNoTracking()
                                           .SingleAsync(d => d.ProductID == ((Product)exceptionEntry.Entity).ProductID);
                    var databaseEntry = _context.Entry(databaseEntity);                    
                    ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                   + "was modified by another user after you got the original value. The "
                   + "edit operation was canceled and the current values in the database "
                   + "have been displayed. If you still want to edit this record, click "
                   + "the Save button again. Otherwise click the Back to List hyperlink.");
                    productToUpdate.RowVersion = (byte[])databaseEntry.Property("RowVersion").CurrentValue;
                    ModelState.Remove("RowVersion");
                }

            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);


            //if (ModelState.IsValid)
            //{
            //    try
            //    {

src/QualityHats/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>

<div class="page-title">
    <p><span style="font-size:large;"><strong><span style="font-family: Calibri;"><span style="color: #000000;">Our Shop</span></span></strong></span></p>
    <p><span style="font-size: medium;"><span style="font-family: Calibri;"><span style="color: #000000;">We are New Zealand&rsquo;s original hat shop, established in 2003, and born from a true passion for headwear; we&rsquo;ve been manufacturing headwear since 1992. </span></span><span style="font-family: Calibri;"><span style="color: #000000;">We have an extensive range of headwear, from hats made onsite to carefully selected imported headwear. </span></span><span style="font-family: Calibri;"><span style="color: #000000;">With the largest range of hats in New Zealand, we are sure you&rsquo;ll be happy you came on by.</span></span></span></p>
    <p><span style="font-family: Calibri; font-size: Large;"><span style="color: #000000;"><strong>Our Location</strong><strong>:</strong></span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">Cambridge Road</span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">Mt Albert</span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">Auckland</span></span></p>
    <p><span style="font-family: Calibri; font-size: Large;"><span style="color: #000000;"><strong>Shop Hours</strong>:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">Monday&ndash;Friday: &nbsp;9.00 am -5.00 pm</span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">Saturday:&nbsp; 9.30 am -12.30 pm</span></span></p>
    <p><span style="font-family: Calibri; font-size: Large;"><span style="color: #000000;"><strong>Phone</strong>:</span></span></p>
    <p><span style="font-family: Calibri; font-size: medium;"><span style="color: #000000;">00 123456</span></span></p>
    <p><span style="font-size: Large;"><strong><span style="font-family: Calibri;"><span style="color: #000000;">Email:</span></span></strong></span></p>
    <p><span style="font-size: medium;"><a href="mailto:sales@qualityhats.com"><span style="font-family: Calibri; color: #0000ff;">sales@qualityhats.com</span></a><span style="color: #000000;"><span style="font-family: Calibri;"> </span></span></span></p>
</div>

src/QualityHats/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<div class="page-title">
    <h2>Contact Us</h2>
</div>
<div class="block-address">
    <div class="block-content">
        <p><h2>Customer Service</h2></p><br />
        <p>
            Cambridge Road, Mt Albert<br />
            PO Box 15-346, Mt Albert<br />
            Auckland, New Zealand
        </p><br />
        <p><strong>Phone: </strong> 00-123456</p>
        <p><strong>Email: </strong>customer@qualityhat.com</p>
    </div>
    <div>
        <br />
        <p><strong>Business Hours</strong>
        <p>Mon-Fri: 9.00am - 5.00pm<br /> Sat: 9.30am - 12.30pm</p>
    </div>
</div>
<div class="map1 col-md-7">
    <iframe width="600" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3191.400171611468!2d174.7055693148244!3d-36.880773979932066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6d0d4720a3564dcf%3A0xac4fd7893e9a560f!2sUnitec+Institute+of+Technology!5e0!3m2!1sen!2snz!4v1505698408071&amp;output=embed"></iframe>
    <br />
    <small>
        <a href="https://goo.gl/maps/CdEfAgBTKjA2" style="color:#8E9196;text-align:left">View Larger Map</a>
    </small>
</div><div id="messages_product_view"></div>
<br />

src/QualityHats/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/Cover2/hat1.jpg" alt="Quality Hats" class="img-responsive" />
            <div class="carousel-caption" role="option">
            @if (!User.IsInRole("Admin"))
            {
                <p>
                    <a class="btn btn-default" asp-area="" asp-controller="MemberProducts" asp-action="Index">
                        Shop Now
                    </a>

                </p>
            }                
            </div>
        </div>
        <div class="item">
            <img src="~/images/Cover2/hat2.jpg" alt="Quality Hats" class="img-responsive" />
            <div class="carousel-caption" role="option">
            @if (!User.IsInRole("Admin"))
            {
                    <p>
                        <a class="btn btn-default" asp-area="" asp-controller="MemberProducts" asp-action="Index">
                            Shop Now
                        </a>

                    </p>
             }                
            </div>
        </div>
        <div class="item">
            <img src="~/images/Cover2/hat3.jpg" alt="Quality Hats" class="img-responsive" />
            <div class="carousel-caption" role="option">
            @if (!User.IsInRole("Admin"))
            {
                    <p>
                        <a class="btn btn-default" asp-area="" asp-controller="MemberProducts" asp-action="Index">
                            Shop Now
                        </a>

                    </p>
             }                
            </div>
        </div>
        <div class="item">
            <img src="~/images/Cover2/hat4.jpg" alt="Quality Hats" class="img-responsive" />
            <div class="carousel-caption" role="option">
            @if (!User.IsInRole("Admin"))
            {
                    <p>
                        <a class="btn btn-default" asp-area="" asp-controller="MemberProducts" asp-action="Index">
                            Shop Now
                        </a>

                    </p>
             }                
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4" >
        <h2>Products Info</h2>
        <div class="alert alert-success">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tristique commodo lacus, at varius arcu euismod vel. In elementum diam nec turpis facilisis, sit amet varius justo vestibulum. Aliquam sit amet aliquet neque. Curabitur eu turpis fringilla, rutrum nisi sed, rutrum dui.</p>
            <br />
            @if (User.IsInRole("Admin"))
            {
                <a class="btn btn-default col-lg-offset-3" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
            }
            else
            {
                <a class="btn btn-default col-lg-offset-3" asp-area="" asp-controller="MemberProducts" asp-action="Index">Products</a>
            }
        </div>     
    </div>
    <div class="col-md-4">
        <h2>Contact US</h2>
        <div class="alert alert-success">
            <p>Morbi eu sodales nisl. Vivamus in pellentesque est, sed feugiat orci. Duis eu augue non turpis vulputate molestie ac nec urna. Praesent a nisi tellus. Aenean elementum elit viverra sodales placerat. Suspendisse lorem nisi, dignissim nec mauris sit amet, fringilla tincidunt ipsum.</p>
            <br />
            <a class="btn btn-default col-lg-offset-3" asp-area="" asp-controller="Home" asp-action="Contact">Contact US</a>
        </div>
    </div>
    <div class="col-md-4">
        <h2>Membership</h2>
        <div class="alert alert-success">
            <p>Praesent ligula sapien, lacinia eget erat sed, ullamcorper elementum nisl. Mauris condimentum tempor lorem quis tempor. Quisque sit amet ornare lacus. In vulputate nunc eu nisl dictum dapibus. Duis tincidunt tempor imperdiet. Curabitur bibendum nibh ipsum.</p>
            <br />
            <a class="btn btn-default col-lg-offset-3" asp-area="" asp-controller="Account" asp-action="Register">Join US</a>
        </div>
    </div>   
</div>